CREATE DATABASE vivaldi;
USE vivaldi;
CREATE USER 'vivaldi'@'localhost' IDENTIFIED BY 'vivaldi';
GRANT ALL PRIVILEGES ON * . * TO 'newuser'@'localhost';
CREATE TABLE shot (ID MEDIUMINT NOT NULL AUTO_INCREMENT, date_column DATETIME DEFAULT CURRENT_TIMESTAMP, favourite VARCHAR(5), time FLOAT, mark MEDIUMINT, comment VARCHAR(2000), PRIMARY KEY (ID));
CREATE TABLE timer (ID MEDIUMINT NOT NULL AUTO_INCREMENT, active VARCHAR(10), event VARCHAR(10), boiler VARCHAR(10), time TIME(0), Monday VARCHAR(10), Tuesday VARCHAR(10), Wednesday VARCHAR(10), Thursday VARCHAR(10), Friday VARCHAR(10), Saturday VARCHAR(10), Sunday VARCHAR(10), PRIMARY KEY (ID));
CREATE TABLE users (ID MEDIUMINT NOT NULL AUTO_INCREMENT, user VARCHAR(50), password VARCHAR(50), allow_config VARCHAR(3), allow_users VARCHAR(3), PRIMARY KEY (ID));
CREATE TABLE config (name VARCHAR(50), value VARCHAR(50));
